/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/BackTop.vue')['default']
    Comments: typeof import('./src/components/Comments.vue')['default']
    Container: typeof import('./src/components/layouts/Container.vue')['default']
    Copyright: typeof import('./src/components/Copyright.vue')['default']
    Footer: typeof import('./src/components/layouts/Footer.vue')['default']
    Header: typeof import('./src/components/layouts/Header.vue')['default']
    Image: typeof import('./src/components/Image.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    PostFilter: typeof import('./src/components/PostFilter.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    TOC: typeof import('./src/components/TOC.vue')['default']
  }
}
