/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./src/components/vue/BackTop.vue')['default']
    ColorModeSwitch: typeof import('./src/components/vue/ColorModeSwitch.vue')['default']
    Comments: typeof import('./src/components/vue/Comments.vue')['default']
    Container: typeof import('./src/components/vue/layouts/Container.vue')['default']
    Copyright: typeof import('./src/components/vue/Copyright.vue')['default']
    Footer: typeof import('./src/components/vue/layouts/Footer.vue')['default']
    Header: typeof import('./src/components/vue/Header.vue')['default']
    Image: typeof import('./src/components/vue/Image.vue')['default']
    Post: typeof import('./src/components/vue/Post.vue')['default']
    PostCard: typeof import('./src/components/vue/PostCard.vue')['default']
    PostFilter: typeof import('./src/components/vue/PostFilter.vue')['default']
    PostList: typeof import('./src/components/vue/PostList.vue')['default']
    TOC: typeof import('./src/components/vue/TOC.vue')['default']
  }
}
