// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FeAvatar: typeof import('@fect-ui/vue')['Avatar']
    FeButton: typeof import('@fect-ui/vue')['Button']
    FeCard: typeof import('@fect-ui/vue')['Card']
    FeGrid: typeof import('@fect-ui/vue')['Grid']
    FeGridGroup: typeof import('@fect-ui/vue')['GridGroup']
    FeInputNumber: typeof import('@fect-ui/vue')['InputNumber']
    FeLink: typeof import('@fect-ui/vue')['Link']
    FeThemeProvide: typeof import('@fect-ui/vue')['ThemeProvide']
    FeUser: typeof import('@fect-ui/vue')['User']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
